[package]
name = "ikea-led"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3

[profile.dev.package.esp-wifi]
opt-level = 3

[profile.dev.package.esp-hal]
opt-level = 3

[dependencies]
esp-hal = { version = "0.17.0", features = [
    "esp32s3",
    "async",
    "embassy",
    "embassy-time-timg0",
    "embassy-executor-thread",
], default-features = false }
esp-wifi = { version = "0.5.1", features = [
    "esp32s3",
    "embassy-net",
    "log",
    "ipv4",
    "tcp",
    "icmp",
    "igmp",
    "dhcpv4",
    "wifi",
], default-features = false }
esp-backtrace = { version = "0.11.0", features = [
    "esp32s3",
    "panic-handler",
    "exception-handler",
    "println",
] }
esp-println = { version = "0.9.0", features = ["esp32s3", "log"] }


embassy-time = { version = "0.3.0", features = ["generic-queue-8"] }
embassy-executor = { version = "0.5.0", features = ["task-arena-size-65536"] }
embassy-sync = "0.5.0"
embassy-net = { version = "0.4.0", features = [
    "medium-ethernet",
    "medium-ip",
    "proto-ipv4",
    "tcp",
    "udp",
] }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-svc = { version = "0.27.0", default-features = false }

micromath = "2.1.0"
static_cell = { version = "2.1.0", features = ["nightly"] }
log = "0.4.20"
smoltcp = { version = "0.11.0", features = [
    "proto-ipv4",
], default-features = false }
heapless = "0.8.0"
chrono = { version = "0.4.31", default-features = false }
byteorder = { version = "1.5.0", default-features = false }
