const O: u8 = 0;
const X: u8 = 255;
pub const DIGITS_3_5: [[[u8; 3]; 5]; 10] = [
    [[O, X, O], [X, O, X], [X, O, X], [X, O, X], [O, X, O]],
    [[O, X, O], [X, X, O], [O, X, O], [O, X, O], [X, X, X]],
    [[X, X, O], [O, O, X], [O, X, O], [X, O, O], [X, X, X]],
    [[X, X, X], [O, O, X], [X, X, X], [O, O, X], [X, X, X]],
    [[O, O, X], [O, X, X], [X, O, X], [X, X, X], [O, O, X]],
    [[X, X, X], [X, O, O], [X, X, O], [O, O, X], [X, X, O]],
    [[X, X, X], [X, O, O], [X, X, X], [X, O, X], [X, X, X]],
    [[X, X, X], [O, O, X], [O, X, O], [X, O, O], [X, O, O]],
    [[X, X, X], [X, O, X], [X, X, X], [X, O, X], [X, X, X]],
    [[X, X, X], [X, O, X], [X, X, X], [O, O, X], [X, X, X]],
];

pub const DIGITS_7_7: [[[u8; 7]; 7]; 10] = [
    [
        [O, X, X, X, X, X, O],
        [X, X, O, O, O, X, X],
        [X, X, O, O, O, X, X],
        [X, X, O, O, O, X, X],
        [X, X, O, O, O, X, X],
        [X, X, O, O, O, X, X],
        [O, X, X, X, X, X, O],
    ],
    [
        [O, O, O, X, X, O, O],
        [O, O, X, X, X, O, O],
        [O, X, X, X, X, O, O],
        [O, O, O, X, X, O, O],
        [O, O, O, X, X, O, O],
        [O, O, O, X, X, O, O],
        [O, X, X, X, X, X, X],
    ],
    [
        [O, X, X, X, X, X, O],
        [X, X, O, O, O, X, X],
        [O, O, O, O, O, X, X],
        [O, O, O, X, X, X, O],
        [O, X, X, X, O, O, O],
        [X, X, O, O, O, O, O],
        [X, X, X, X, X, X, X],
    ],
    [
        [O, X, X, X, X, X, O],
        [O, O, O, O, O, X, X],
        [O, O, O, O, O, X, X],
        [O, O, X, X, X, X, O],
        [O, O, O, O, O, X, X],
        [O, O, O, O, O, X, X],
        [O, X, X, X, X, X, O],
    ],
    [
        [X, X, O, O, O, O, O],
        [X, X, O, O, O, O, O],
        [X, X, O, O, X, X, O],
        [X, X, O, O, X, X, O],
        [X, X, X, X, X, X, X],
        [O, O, O, O, X, X, O],
        [O, O, O, O, X, X, O],
    ],
    [
        [X, X, X, X, X, X, X],
        [X, X, O, O, O, O, O],
        [X, X, O, O, O, O, O],
        [X, X, X, X, X, X, O],
        [O, O, O, O, O, X, X],
        [O, O, O, O, O, X, X],
        [X, X, X, X, X, X, O],
    ],
    [
        [O, X, X, X, X, X, O],
        [X, X, O, O, O, O, O],
        [X, X, O, O, O, O, O],
        [X, X, X, X, X, X, O],
        [X, X, O, O, O, X, X],
        [X, X, O, O, O, X, X],
        [O, X, X, X, X, X, O],
    ],
    [
        [X, X, X, X, X, X, X],
        [O, O, O, O, O, X, X],
        [O, O, O, O, X, X, O],
        [O, O, X, X, X, O, O],
        [O, X, X, O, O, O, O],
        [X, X, O, O, O, O, O],
        [X, X, O, O, O, O, O],
    ],
    [
        [O, X, X, X, X, X, O],
        [X, X, O, O, O, X, X],
        [X, X, O, O, O, X, X],
        [O, O, X, X, X, O, O],
        [X, X, O, O, O, X, X],
        [X, X, O, O, O, X, X],
        [O, X, X, X, X, X, O],
    ],
    [
        [O, X, X, X, X, X, O],
        [X, X, O, O, O, X, X],
        [X, X, O, O, O, X, X],
        [O, X, X, X, X, X, X],
        [O, O, O, O, O, X, X],
        [O, O, O, O, O, X, X],
        [O, X, X, X, X, X, O],
    ],
];
